### ISSUE TITLE
Update Flatpak To Support Heroic Games Launcher's Legendary Config File Location Change

### ISSUE THREAD

**Issue by Kaympe20** [flathub/io.github.philipk.boilr#23]
@PhilipK [You recently readded support for Heroic Games Launcher](https://github.com/PhilipK/BoilR/pull/370). Can you update the Flatpak manifest to support this change?

**Comment by PhilipK** [comment]
This should do it:
https://github.com/PhilipK/BoilR/commit/aba6c7f8342a533ff377e35ec029c202854bd563

But it might take a while for flathub to build and send out new versions (hours, not minutes)

**Comment by PhilipK** [comment]
I also added the Heroic bin (non flatpak) folder now, just to be sure.
